### PR TITLE
fix issue #11

### PR DESCRIPTION
**Pull request by bioinfornatics**
format for PEP8 and fix issue 11

### CODE REVIEW

**Comment by bioinfornatics** [comment]
it seems that the integration continue is broken.
working in progress

**Comment by bioinfornatics** [comment]
My feature request works as expected
Currently, CI is broken but I think, is not part of my change.
Indeed travis build `likwid` from master so new and old symbol could be missing

```
Traceback (most recent call last):
  File "./tests//testpin.py", line 3, in <module>
    import pylikwid
ImportError: /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pylikwid.so: undefined symbol: power_names

```

@TomTheBear could you review it, please?

**Comment by TomTheBear** [comment]
I'm currently in my annual holiday with very limited internet access. I'll check it as soon as I'm back (February)

**Comment by bioinfornatics** [comment]
Thanks,
have a good break

**Pull request merged**
